# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 James Braid
"""Immutable generation snapshot collection and preview construction."""

from __future__ import annotations

import hashlib
import stat
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from .cleaner import VarRef, clean_resource, normalize_emitted, strip_secret_shaped
from .config import Config
from .controller import Controller
from .controller_projection import build_controller_snapshot
from .coverage import (
    CoverageReport,
    audit_coverage_snapshot,
    collect_coverage_snapshot,
    render_coverage_md,
)
from .enumerator import enumerate_controller
from .errors import TofuExecutionError, UbitofuError
from .file_metadata import inspect_file_metadata, require_supported_metadata
from .file_transaction import prepare_transaction
from .hcl_writer import render_resource, render_variables
from .import_emitter import assign_slugs, render_import
from .module_index import (
    IndexedImport,
    IndexedVariable,
    ModuleIndex,
    index_effective_module,
    reindex_module,
)
from .outcomes import (
    CommandOutcome,
    OutcomeItem,
    digest_active_source,
    digest_controller_observations,
    digest_provider_schema,
    opaque_reference,
)
from .reconcile_model import (
    ControllerSnapshot,
    FileIdentity,
    ProviderSchema,
    parse_opentofu_address,
)
from .reconcile_renderer import ProposedFile
from .runtime import RuntimeSession, generation_import_scaffold
from .secrets import resolve_secrets
from .tofu_json import parse_provider_schema, validate_document_header
from .tofu_runner import TofuRunner
from .values import FrozenObject, FrozenValue, freeze_value

_OWNERSHIP_MARKER = b"# ubitofu: generated\n"
_COVERAGE_MARKER = b"# Provider coverage\n\nGenerated by `ubitofu`"
_NEW_FILE_MODE = stat.S_IFREG | 0o644
_OWNED_PATHS = frozenset(
    {
        PurePosixPath("generated.tf"),
        PurePosixPath("generated.tofu"),
        PurePosixPath("generated_new.tf"),
        PurePosixPath("generated_new.tofu"),
        PurePosixPath("imports.tf"),
        PurePosixPath("imports.tofu"),
        PurePosixPath("unifi-variables.tf"),
        PurePosixPath("unifi-variables.tofu"),
        PurePosixPath("COVERAGE.md"),
    }
)


@dataclass(frozen=True)
class GeneratedResource:
    """Provider-shaped values retained from one strict generated plan."""

    address: str
    resource_type: str
    name: str
    values: FrozenObject


def parse_generated_resources(
    value: object,
    *,
    expected_addresses: frozenset[str] | None = None,
) -> tuple[GeneratedResource, ...]:
    """Retain only root managed resources needed by the generation renderer."""
    _, document = validate_document_header(value, kind="plan")
    planned = _strict_mapping(document.get("planned_values"))
    root = _strict_mapping(planned.get("root_module"))
    if expected_addresses is None and root.get("child_modules") not in (None, []):
        raise ValueError("unsupported generated resource")
    rows = root.get("resources", [])
    if not isinstance(rows, list):
        raise ValueError("unsupported generated resource")
    resources: dict[str, GeneratedResource] = {}
    for raw in rows:
        row = _strict_mapping(raw)
        address = row.get("address")
        if expected_addresses is not None and address not in expected_addresses:
            continue
        mode = row.get("mode")
        resource_type = row.get("type")
        name = row.get("name")
        raw_values = row.get("values")
        if (
            not isinstance(address, str)
            or mode != "managed"
            or not isinstance(resource_type, str)
            or not isinstance(name, str)
            or not isinstance(raw_values, Mapping)
        ):
            raise ValueError("unsupported generated resource")
        try:
            parsed = parse_opentofu_address(address)
        except ValueError as exc:
            raise ValueError("unsupported generated resource") from exc
        if (
            parsed.module is not None
            or parsed.mode != "managed"
            or parsed.index is not None
            or parsed.resource_type != resource_type
            or parsed.name != name
        ):
            raise ValueError("unsupported generated resource")
        frozen = freeze_value(raw_values)
        if not isinstance(frozen, FrozenObject):
            raise ValueError("unsupported generated resource")
        if address in resources:
            raise ValueError("duplicate generated resource")
        resources[address] = GeneratedResource(address, resource_type, name, frozen)
    if expected_addresses is not None and set(resources) != expected_addresses:
        raise ValueError("generated plan does not match enumerated imports")
    return tuple(resources[address] for address in sorted(resources))


def capture_generate_source_identities(
    *, workdir: Path, module: ModuleIndex
) -> tuple[FileIdentity, ...]:
    """Capture supported metadata and hashes for every active source."""
    worktree_uid = workdir.resolve(strict=True).stat().st_uid
    identities: list[FileIdentity] = []
    for source in module.sources:
        if not source.active:
            continue
        inspection = inspect_file_metadata(
            workdir / source.relative_path,
            relative_path=source.relative_path,
        )
        identity = require_supported_metadata(inspection, worktree_uid=worktree_uid)
        if (
            identity.size != len(source.source)
            or identity.sha256 != hashlib.sha256(source.source).hexdigest()
        ):
            raise ValueError("source changed during collection")
        identities.append(identity)
    coverage_path = PurePosixPath("COVERAGE.md")
    coverage = workdir / coverage_path
    if coverage.exists():
        content = coverage.read_bytes()
        if content.startswith(_COVERAGE_MARKER):
            identities.append(
                require_supported_metadata(
                    inspect_file_metadata(coverage, relative_path=coverage_path),
                    worktree_uid=worktree_uid,
                )
            )
    return tuple(sorted(identities, key=lambda item: item.relative_path))


@dataclass(frozen=True)
class GenerateSnapshot:
    """All immutable facts consumed by one generation preview."""

    controller: ControllerSnapshot
    schema: ProviderSchema
    module: ModuleIndex
    imports: tuple[IndexedImport, ...]
    variables: tuple[IndexedVariable, ...]
    coverage: tuple[OutcomeItem, ...]
    coverage_report: CoverageReport
    source_identities: tuple[FileIdentity, ...]
    resources: tuple[GeneratedResource, ...]


@dataclass(frozen=True)
class GeneratePreview:
    snapshot: GenerateSnapshot
    candidates: tuple[ProposedFile, ...]
    changed_paths: tuple[PurePosixPath, ...]
    candidate_digests: tuple[tuple[PurePosixPath, str | None], ...]
    findings: tuple[OutcomeItem, ...]

    @property
    def blocked(self) -> bool:
        return any(item.severity == "blocking" for item in self.findings)


def render_generate(snapshot: GenerateSnapshot) -> GeneratePreview:
    """Render and structurally validate the complete generated module overlay."""
    if any(item.severity == "blocking" for item in snapshot.coverage):
        return _blocked_preview(snapshot, "coverage")
    resource_chunks: list[bytes] = []
    required_variables: set[str] = set()
    schema_by_type = dict(snapshot.schema.resources)
    for resource in sorted(snapshot.resources, key=lambda item: item.address):
        schema = schema_by_type.get(resource.resource_type)
        if schema is None:
            return _blocked_preview(snapshot, "unsupported-resource")
        rendered, variable_names = _render_generated_resource(resource, schema)
        required_variables.update(variable_names)
        resource_chunks.append(rendered)

    desired: dict[PurePosixPath, bytes | None] = {}
    if resource_chunks:
        desired[PurePosixPath("generated.tf")] = _OWNERSHIP_MARKER + b"\n".join(
            resource_chunks
        )
    if snapshot.imports:
        desired[PurePosixPath("imports.tf")] = _OWNERSHIP_MARKER + b"\n".join(
            render_import(item.address, item.import_id).encode()
            for item in sorted(snapshot.imports, key=lambda item: item.address)
        )
    external_variables = {
        item.name
        for item in snapshot.variables
        if item.source_path
        not in {
            PurePosixPath("unifi-variables.tf"),
            PurePosixPath("unifi-variables.tofu"),
        }
    }
    generated_variables = required_variables - external_variables
    if generated_variables:
        desired[PurePosixPath("unifi-variables.tf")] = _OWNERSHIP_MARKER + render_variables(
            sorted(generated_variables)
        ).encode()
    desired[PurePosixPath("COVERAGE.md")] = render_coverage_md(
        snapshot.coverage_report
    ).encode()
    sources = {source.relative_path: source.source for source in snapshot.module.sources}
    identities = {identity.relative_path: identity for identity in snapshot.source_identities}
    for path in sorted(_OWNED_PATHS):
        source_bytes = sources.get(path)
        if source_bytes is None and path == PurePosixPath("COVERAGE.md"):
            if path in identities:
                continue
        if source_bytes is None:
            continue
        marker = _COVERAGE_MARKER if path.suffix == ".md" else _OWNERSHIP_MARKER
        if not source_bytes.startswith(marker):
            if path in desired:
                return _blocked_preview(snapshot, "source-ownership")
            continue
        if path not in desired:
            desired[path] = None
    try:
        reindex_module(
            snapshot.module,
            tuple(
                sorted(
                    (path, candidate)
                    for path, candidate in desired.items()
                    if path.suffix != ".md"
                )
            ),
        )
    except (OSError, RuntimeError, ValueError):
        return _blocked_preview(snapshot, "candidate-module")
    # Non-HCL owned outputs are detached from ModuleIndex but still identity-bound.
    coverage_path = PurePosixPath("COVERAGE.md")
    coverage_identity = identities.get(coverage_path)
    if coverage_identity is not None and coverage_path not in sources:
        sources[coverage_path] = _read_identity_source_unavailable(coverage_identity)
    files: list[ProposedFile] = []
    for path, candidate in sorted(desired.items()):
        original_identity = identities.get(path)
        candidate_digest = None if candidate is None else hashlib.sha256(candidate).hexdigest()
        if (
            candidate is not None
            and original_identity is not None
            and original_identity.sha256 == candidate_digest
        ):
            continue
        if sources.get(path) == candidate:
            continue
        if path in sources and original_identity is None:
            return _blocked_preview(snapshot, "source-identity")
        digest = candidate_digest
        files.append(
            ProposedFile(
                path,
                original_identity,
                candidate,
                digest,
                _NEW_FILE_MODE if original_identity is None else original_identity.mode,
            )
        )
    candidates = tuple(files)
    return GeneratePreview(
        snapshot,
        candidates,
        tuple(item.relative_path for item in candidates),
        tuple((item.relative_path, item.candidate_sha256) for item in candidates),
        (
            OutcomeItem(
                "generation_preview", "info", None, "generation preview is ready"
            ),
        ),
    )


def _render_generated_resource(
    resource: GeneratedResource, schema: FrozenObject
) -> tuple[bytes, set[str]]:
    """Render one policy-safe resource and report its referenced variables."""
    values = _thaw_object(resource.values)
    schema_value = _thaw_object(schema)
    refs, lifecycle, suppress = resolve_secrets(
        resource.resource_type, resource.name, schema_value
    )
    attrs = clean_resource(values, schema_value, sensitive=refs)
    for attr in suppress:
        attrs.pop(attr, None)
    attrs = normalize_emitted(resource.resource_type, attrs)
    for path in sorted(strip_secret_shaped(attrs)):
        top = path.split(".", 1)[0].split("[", 1)[0]
        ignored = lifecycle.setdefault("ignore_changes", [])
        if top not in ignored:
            ignored.append(top)
    if "ignore_changes" in lifecycle:
        lifecycle["ignore_changes"] = sorted(set(lifecycle["ignore_changes"]))
    block_types = tuple(
        _mapping(_mapping(schema_value.get("block")).get("block_types", {}))
    )
    return (
        render_resource(
            resource.resource_type,
            resource.name,
            attrs,
            lifecycle=lifecycle or None,
            block_attrs=block_types,
        ).encode(),
        _variable_names(attrs),
    )


def _blocked_preview(snapshot: GenerateSnapshot, reason: str) -> GeneratePreview:
    item = OutcomeItem(
        "generation_blocked",
        "blocking",
        opaque_reference(f"generate-blocker:{reason}"),
        "generation preview is blocked",
    )
    findings = snapshot.coverage
    if item not in findings:
        findings += (item,)
    return GeneratePreview(snapshot, (), (), (), findings)


def generate_outcome(preview: GeneratePreview) -> CommandOutcome:
    """Build the bounded public outcome from one immutable generation preview."""
    active_sources = tuple(
        (source.relative_path, source.source)
        for source in preview.snapshot.module.sources
        if source.active
    )
    safe_controller: list[tuple[str, FrozenValue]] = []
    schema_by_type = dict(preview.snapshot.schema.resources)
    imports = {item.address: item.import_id for item in preview.snapshot.imports}
    for resource in preview.snapshot.resources:
        schema = schema_by_type.get(resource.resource_type)
        if schema is None:
            continue
        rendered, _ = _render_generated_resource(resource, schema)
        safe_controller.append(
            (
                resource.address,
                freeze_value(
                    {
                        "rendered_sha256": hashlib.sha256(rendered).hexdigest(),
                        "import_id_sha256": hashlib.sha256(
                            imports.get(resource.address, "").encode()
                        ).hexdigest(),
                    }
                ),
            )
        )
    return CommandOutcome(
        command="generate",
        changed=bool(preview.changed_paths),
        blocked=preview.blocked,
        summary="generation preview complete",
        items=preview.findings,
        input_digests=(
            ("active_source", digest_active_source(active_sources)),
            ("controller", digest_controller_observations(safe_controller)),
            ("provider_schema", digest_provider_schema(preview.snapshot.schema.resources)),
        ),
        payload=freeze_value(
            {
                "changed_paths": [path.as_posix() for path in preview.changed_paths],
                "candidate_digests": [
                    [path.as_posix(), digest]
                    for path, digest in preview.candidate_digests
                ],
            }
        ),
    )


def validate_generate_preview(
    *, workdir: Path, preview: GeneratePreview
) -> GeneratePreview:
    """Recheck captured sources and the exact candidate overlay before preparation."""
    if preview.blocked:
        return preview
    try:
        worktree_uid = workdir.resolve(strict=True).stat().st_uid
        for expected in preview.snapshot.source_identities:
            actual = require_supported_metadata(
                inspect_file_metadata(
                    workdir / expected.relative_path,
                    relative_path=expected.relative_path,
                ),
                worktree_uid=worktree_uid,
            )
            if actual != expected:
                raise ValueError("stale source")
        index_effective_module(
            workdir=workdir,
            candidates=tuple(
                (item.relative_path, item.candidate)
                for item in preview.candidates
                if item.relative_path.suffix in {".tf", ".tofu", ".json"}
            ),
        )
    except (OSError, RuntimeError, ValueError):
        return _blocked_preview(preview.snapshot, "stale-source")
    return preview


def commit_generate(*, session: RuntimeSession, preview: GeneratePreview) -> None:
    """Commit an already-rendered complete generation preview transactionally."""
    checked = validate_generate_preview(workdir=session.workdir, preview=preview)
    if checked.blocked:
        raise UbitofuError("generation preview is blocked")
    transaction = prepare_transaction(workdir=session.workdir, files=checked.candidates)
    transaction.commit()


def _read_identity_source_unavailable(identity: FileIdentity) -> bytes:
    """Represent detached owned content for digest-only no-op comparison."""
    # The caller compares the digest below when bytes are unavailable. A sentinel
    # cannot accidentally compare equal to real candidate bytes.
    return b"\x00identity:" + identity.sha256.encode("ascii")


def _thaw(value: FrozenValue) -> object:
    if isinstance(value, FrozenObject):
        return {key: _thaw(item) for key, item in value.items}
    if isinstance(value, tuple):
        return [_thaw(item) for item in value]
    return value


def _thaw_object(value: FrozenObject) -> dict[str, object]:
    return {key: _thaw(item) for key, item in value.items}


def _mapping(value: object) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ValueError("generation schema value is not an object")
    return value


def _strict_mapping(value: object) -> Mapping[str, object]:
    if not isinstance(value, Mapping) or not all(isinstance(key, str) for key in value):
        raise ValueError("unsupported generated resource")
    return value


def _variable_names(value: object) -> set[str]:
    if isinstance(value, VarRef):
        return {value.expr.removeprefix("var.")}
    if isinstance(value, dict):
        return set().union(*(_variable_names(item) for item in value.values()), set())
    if isinstance(value, list):
        return set().union(*(_variable_names(item) for item in value), set())
    return set()


def collect_generate_snapshot(
    *,
    cfg: Config,
    controller: Controller,
    runner: TofuRunner,
    module: ModuleIndex,
    session: RuntimeSession,
) -> GenerateSnapshot:
    """Collect generation inputs without retaining a generated stub."""
    if Path(cfg.workdir).resolve(strict=True) != runner.workdir.resolve(strict=True):
        raise ValueError("generation workdir mismatch")
    if session.workdir != runner.workdir.resolve(strict=True):
        raise ValueError("generation workdir mismatch")
    initial_identities = capture_generate_source_identities(
        workdir=runner.workdir, module=module
    )
    enumeration = enumerate_controller(controller, capture_records=True)
    raw_records = tuple(
        (record.resource_type, record.import_id, _thaw_object(record.raw))
        for record in enumeration.records
    )
    controller_snapshot = build_controller_snapshot(
        records=raw_records,
        covered_resource_types=tuple(enumeration.covered_resource_types),
        name_hints={
            (target.resource_type, target.import_id): target.name_hint
            for target in enumeration.targets
        },
    )
    assigned = assign_slugs(
        sorted(
            enumeration.targets,
            key=lambda item: (item.resource_type, item.import_id, item.name_hint),
        )
    )
    import_path = PurePosixPath(
        "imports.tofu"
        if any(
            source.active and source.relative_path.suffix == ".tofu"
            for source in module.sources
        )
        else "imports.tf"
    )
    imports = tuple(
        sorted(
            (
                IndexedImport(
                    f"{target.resource_type}.{slug}", target.import_id, import_path
                )
                for target, slug in assigned
            ),
            key=lambda item: item.address,
        )
    )
    if len({item.address for item in imports}) != len(imports) or len(
        {(item.address, item.import_id) for item in imports}
    ) != len(imports):
        raise ValueError("duplicate generated import ownership")
    bootstrap_conflict = any(
        _is_unifi_address(item.address) for item in module.resources
    ) or any(_is_unifi_address(item.address) for item in module.imports)
    resources: tuple[GeneratedResource, ...] = ()
    if imports and not bootstrap_conflict:
        scaffold = _OWNERSHIP_MARKER + b"\n".join(
            render_import(item.address, item.import_id).encode()
            for item in sorted(imports, key=lambda item: item.address)
        )
        failure: BaseException | None = None
        with generation_import_scaffold(session, scaffold):
            try:
                plan_exit = runner.plan(
                    out=session.plan_path, generate_config_out=session.generated_path
                )
                if plan_exit not in {0, 2}:
                    raise TofuExecutionError("plan", plan_exit, "execution failed")
            except BaseException as exc:
                # Do not propagate immutable typed exceptions through
                # contextlib's generator traceback assignment on Python 3.14.
                failure = exc
        if failure is not None:
            if session.generated_path.exists():
                session.generated_path.unlink()
            raise failure
        try:
            generated_document = runner.show_json(session.plan_path)
        except BaseException:
            if session.generated_path.exists():
                session.generated_path.unlink()
            raise
        resources = parse_generated_resources(
            generated_document,
            expected_addresses=frozenset(item.address for item in imports),
        )
    raw_schema = runner.providers_schema()
    schema = parse_provider_schema(raw_schema)
    coverage_report = audit_coverage_snapshot(
        collect_coverage_snapshot(controller), raw_schema
    )
    findings: list[OutcomeItem] = [
        OutcomeItem(
            "coverage_gap",
            "warning",
            opaque_reference(f"coverage:{finding.kind}:{finding.identifier}"),
            "controller coverage is incomplete",
        )
        for finding in coverage_report.gaps
    ]
    findings.extend(
        OutcomeItem(
            "coverage_gap",
            "warning",
            opaque_reference(f"enumeration:{gap}"),
            "controller coverage is incomplete",
        )
        for gap in enumeration.gaps
    )
    if findings:
        findings.append(
            OutcomeItem(
                "generation_blocked",
                "blocking",
                opaque_reference("generate-blocker:coverage"),
                "generation preview is blocked",
            )
        )
    if bootstrap_conflict:
        findings.append(
            OutcomeItem(
                "generation_blocked",
                "blocking",
                opaque_reference("generate-blocker:existing-unifi-ownership"),
                "generation preview is blocked",
            )
        )
    final_identities = capture_generate_source_identities(
        workdir=runner.workdir, module=module
    )
    if final_identities != initial_identities:
        findings.append(
            OutcomeItem(
                "generation_blocked",
                "blocking",
                opaque_reference("generate-blocker:stale-source"),
                "generation preview is blocked",
            )
        )
    return GenerateSnapshot(
        controller_snapshot,
        schema,
        module,
        imports,
        module.variables,
        tuple(findings),
        coverage_report,
        initial_identities,
        resources,
    )


def _is_unifi_address(address: str) -> bool:
    try:
        return parse_opentofu_address(address).resource_type.startswith("unifi_")
    except ValueError:
        return True


def prepare_generate(
    *,
    cfg: Config,
    controller: Controller,
    runner: TofuRunner,
    session: RuntimeSession,
) -> GeneratePreview:
    """Collect and validate one complete preview under the caller's runtime lock."""
    if Path(cfg.workdir).resolve(strict=True) != session.workdir:
        raise ValueError("generation workdir mismatch")
    module = index_effective_module(workdir=session.workdir)
    snapshot = collect_generate_snapshot(
        cfg=cfg,
        controller=controller,
        runner=runner,
        module=module,
        session=session,
    )
    return validate_generate_preview(
        workdir=session.workdir,
        preview=render_generate(snapshot),
    )
